name: Docker Image CI

on: [push]

strategy:
  matrix:
    compiler: [gcc, clang]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      env:
        CC: ${{ matrix.compiler }}
    - run: docker build . --file Dockerfile --tag geant4:base-$(date +%s) --target base 
    - name: Build the Docker image geant4-lib 
      run: docker build . --file Dockerfile --tag geant4:lib-$(date +%s) --target geant4-base
